### ISSUE TITLE
missing step to install dapr on kubernetes cluster

### ISSUE THREAD

**Issue by ahmedbham** [radius-project/docs#1013]
**URL of the docs page**
https://docs.radapp.io/tutorials/dapr/

**How is it currently worded?**

**How should it be worded?**
Between Step 2 and Step 3, need to add step to install dapr on kubernetes cluster

**Screenshots**

**Additional context**

[AB#10799](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10799)

**Comment by willtsai** [comment]
Hi @ahmedbham - thank you for filing this issue! We looked into it and have determined that the Dapr installation instructions were included as a part of the [Prerequisites](https://docs.radapp.io/tutorials/dapr/#prerequisites). This is how we document non-Radius dependencies to keep our Tutorials succinct and avoid documenting instructions for using tools from other projects since those might be subject to change outside of Radius' control. If you have further concerns or suggestions, please feel free to reopen this issue. Thanks again!
