### ISSUE TITLE
Add fancy copy tools to only copy certain code blocks 

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#148]
Suggestions from https://github.com/Azure/radius/pull/246: 

- We have the ability to have a code block where the new content is highlighted visually
- The copy button copies the new content (or there are two copy buttons)

**Reasoning**
In our tutorials we sometimes show abbreviated versions of template.bicep. If users are moving too quickly and copy a `...` line into their template.bicep, it won't deploy properly.

[AB#1121](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/1121)

[AB#7083](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7083)

**Comment by emily-potyraj** [comment]
also find a way to remove copy button from example output blocks

**Comment by rynowak** [comment]
@AaronCrawfis - is this still relevant with the updates to how we display code blocks? Please close if no longer relevant.

**Comment by AaronCrawfis** [comment]
> @AaronCrawfis - is this still relevant with the updates to how we display code blocks? Please close if no longer relevant.

Still relevant for Tutorials. We need a better way to bridge the gap between "Here's the code you need to copy and paste" vs. "Here's how your code fits in with the rest of the code".

In an ideal solution you can see a large code block, and hovering over specific blocks will bring up a copy button which you can click to only copy the highlighted section, instead of one button copying everything.

**Comment by AaronCrawfis** [comment]
Not planned
