### ISSUE TITLE
Revamp admin guides

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/docs#232]
### Introduction 
Currently, some of the topics under admin guides need a correct placement to enable users to find the content intuitively and also understand the concepts of Radius

### Template 
**Admin guides**
- Platforms 
   - Kubernetes
      - Set up a cluster
      - Install the control plane 
      - Add a cloud provider 
   - Azure service (Future)
- Radius Environments
   - Initialize environments
   - Operate on multiple environments 
- Health
- CI/CD

[AB#7096](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7096)

**Comment by AaronCrawfis** [comment]
As part of #230 there's a new Kubernetes platform page. We should add the section on how to initialize the control-plane on Kubernetes there.

**Comment by Reshrahim** [comment]
@AaronCrawfis - What do you think about having a separate page for the installation of the control plane services under admin guides as the scope is larger
 
**.12**
1. Installation of control plane 
2. Uninstallation of control plane 
3. Installation of the control plane in interactive mode with Azure cloud provider
4. Installation of the control plane with cloud provider flags 

**Future versions**
1. Commands to update/delete cloud provider

**Comment by AaronCrawfis** [comment]
In my mind we should bucket "tasks to do" for a given platform (Kubernetes, Azure, etc.) underneath that platform.

With control plane installation, the flow for a user would be "I want to use Kubernetes, let's open that page to learn more about it and learn how to use it." While we can still have a dedicated page on the concept of the control plane and what it is, I would put the content of how to install it within that platform's docs. Especially because environment installation is going to be **very** different for each platform. For example:

- Kubernetes you'll use a Helm chart for production environments.
- (future) Azure you'll need to register the resource providers on your subscription(s)
- (future) Docker you'll most likely use the rad CLI

While the rad CLI could be used for all of these, the platform's primary mechanism (Helm, Azure Portal, etc.) will be used primarily.

So this structure:

```
            Platfoms
           /         \
      Kubernetes     Azure
      /      \      /    \
    Helm     CLI   Portal   CLI
```

seems better than this structure:

        Platform overview             Control Plane
           /         \                /          \
      Kubernetes     Azure          Kubernetes    Azure
                                   /      \      /    \ 
                                 Helm   CLI   Portal CLI

**Comment by AaronCrawfis** [comment]
Also see https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-deploy/ for how Dapr sets this up

**Comment by nicolejms** [comment]
triage: moving to v0.14

**Comment by AaronCrawfis** [comment]
This has been updated over the past couple releases. Closing as there's not much more to do
