### ISSUE TITLE
add direction for how users can customize the container resource

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#395]
This note applies to both our Concepts section and our Tutorial. 

We currently show users example container resources in several places. For example, on the [App model Concept page](https://edge.radapp.dev/concepts/appmodel-concept/#adding-resources):
![image](https://user-images.githubusercontent.com/36576265/196153687-639fd2bc-b90c-4fef-8b57-709bef1779b1.png)

We heard during usability testing:
> It's not clear to me if this example is real. I only see `image: 'myimage'`, but you haven't shown me that I can customize it. I haven't seen anything like, "You will be able to set its memory, environment variables, and scaling." You haven't told me those things are possible, and from the Table of Contents I wouldn't know where to go.

[AB#5243](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5243)

**Comment by Reshrahim** [comment]
I think there is a lot of potential for us to improve the [containers page ](https://docs.radapp.dev/author-apps/container/)under the developer guides. We say model your own container workloads but don't really provide enough guidance to do so. Some of the things we could cover or add more info on 

1. Go deep into the container resource - what is possible? what is simplified?
2. How they could bring their own containers and model them in Radius
3. Cross-link quickstart guides ( mount a volume,inject env variables ) also other references
4. Resource schemas definition - reference a swagger doc or cadl spec so that there is one source of truth instead of us manually updating/ maintaining the schema when there are code changes 

Thoughts?
