### ISSUE TITLE
Administrator or Operator

### ISSUE THREAD

**Issue by ryanwaite** [radius-project/docs#538]
In the table of contents we have Developer Guides and Administrator Guides. I don't think "Administrator" is the right term. Typically we talk about IT Pro or Operators. I'd like us to consider changing Administrator Guides to something like Operator Guides or Operations Guides.

[AB#7468](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7468)

**Comment by shalabhms** [comment]
@AaronCrawfis to  decide on action item here.

**Comment by AaronCrawfis** [comment]
Operator guides is better. We only use "Administrator guides" due to some historical decisions that didn't pan out.

We actually kept operator in the URL path: https://docs.radapp.dev/operations/

We can get this in prior to public release. It's a one line change in docs/content/operations/_index.md
